name: otherstory_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  go_router: ^14.7.2
  pin_code_fields: ^8.0.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
  fonts:
    - family: DaysOne
      fonts:
        - asset: assets/fonts/DaysOne-Regular.ttf
